### ISSUE TITLE
Is this repo still used?

### ISSUE THREAD

**Issue by kevcisme** [databricks-academy/dbacademy#5]
According to 

![Screen Shot 2022-11-08 at 6 20 07 PM](https://user-images.githubusercontent.com/24496260/200737658-0db9c44e-0331-4662-89c3-d21c0023930e.png)

> About
> This archive repository was replaced by dbacademy-rest, dbacademy-gems and dbacademy-courseware

The published branch has no commits < 3 months old but the main branch has commits < 1 week old.

Is the About description off? Courses still load the three repos listed above (dbacademy-rest, dbacademy-gems and dbacademy-courseware)

**Comment by SireInsectus** [comment]
@kevcisme Some time ago, we forked dbacademy into the three notebooks. Recently it was decided to merge them back into a single repo. I'll update the README accordingly.
