### ISSUE TITLE
dbacademy fails to install on cluster

### ISSUE THREAD

**Issue by JimmyMcWeb** [databricks-academy/dbacademy#7]
Library installation attempted on the driver node of cluster 0727-134331-f5wt3kdl and failed. Please refer to the following error message to fix the library or contact Databricks support. 
Error Code: DRIVER_LIBRARY_INSTALLATION_FAILURE. 
Error Message: org.apache.spark.SparkException: 
Process List(bash, /local_disk0/.ephemeral_nfs/cluster_libraries/python/python_start_clusterwide.sh, /local_disk0/.ephemeral_nfs/cluster_libraries/python/bin/pip, install, dbacademy, --index-url, https://github.com/databricks-academy/dbacademy.git, --disable-pip-version-check) exited with code 1. 
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /databricks-academy/dbacademy.git/dbacademy/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /databricks-academy/dbacademy.git/dbacademy/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /databricks-academy/dbacademy.git/dbacademy/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /databricks-academy/dbacademy.git/dbacademy/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /databricks-academy/dbacademy.git/dbacademy/
ERROR: Could not find a version that satisfies the requirement dbacademy (from versions: none)
ERROR: No matching distribution found for dbacademy

Cluster is running: 12.0 ML (includes Apache Spark 3.3.1, Scala 2.12)

Also tried to install on 11.3 and 10.4

**Comment by SireInsectus** [comment]
@JimmyMcWeb I'm sorry, but this repo is only public as an implementation side effect. We don't actually monitor issues or PRs here. But to your specific error, I believe the problem has more to do with network restrictions imposed by your Workspace Admin, where you are prohibited from public reads and not the material itself.
